---
- name: Check if Solr home is already set up
  register: solr_home
  ansible.builtin.stat:
    path: "{{ solr.prefix.home }}/solr.xml"

- name: Install the example home files
  when: not solr_home.stat.exists or solr.overwrite_home
  ansible.posix.synchronize:
    src: "{{ solr.prefix.bin }}/server/solr/"
    dest: "{{ solr.prefix.home }}/"
    delete: true
    recursive: true
    rsync_opts:
      - --chown=solr:solr
      - --no-times
      - --checksum
    use_ssh_args: yes
  notify: Restart Solr
  delegate_to: "{{ inventory_hostname }}"

- name: Comment out unsupported options (Solr 8.x)
  notify: Restart Solr
  when: solr.version is ansible.builtin.version('9', '<')
  loop:
    - allowUrls
    - modules
    - zkCredentialsInjector
    - distributedClusterStateUpdates
    - distributedCollectionConfigSetExecution
    - minStateByteLenForCompression
    - stateCompressor
    - hideStackTrace
  ansible.builtin.lineinfile:
    path: "{{ solr.prefix.home }}/solr.xml"
    regexp: '^(?!<\!\-\-)(.*{{ item }}.*)$'
    line: <!-- deactivated by Ansible \g<1> -->
    state: present
    backrefs: yes

- name: Restore unsupported options (Solr 9.x)
  notify: Restart Solr
  when: solr.version is ansible.builtin.version('9', '>=')
  ansible.builtin.replace:
    path: "{{ solr.prefix.home }}/solr.xml"
    regexp: "^<!-- deactivated by Ansible (.*)-->.*$"
    replace: \g<1>
