---
- name: Install Apache Solr
  ansible.builtin.include_tasks: solr.yaml

- name: Install Apache Tika
  ansible.builtin.include_tasks: tika.yaml

- name: Install Nginx template
  ansible.builtin.include_tasks: nginx.yaml
  when: (inventory_hostname in groups.nginx) | default(True)

- name: Install Apache template
  ansible.builtin.include_tasks: apache.yaml
  when: (inventory_hostname in groups.apache) | default(False)
