---
- name: Create program directory for Solr
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
  with_items:
    - "{{ solr.prefix.bin }}"

- name: Download Solr
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/solr/solr/{{ solr.version }}/solr-{{ solr.version }}.tgz"
    dest: "{{ item }}"
    checksum: "sha512:https://archive.apache.org/dist/solr/solr/{{ solr.version }}/solr-{{ solr.version }}.tgz.sha512"
    owner: root
    group: "{{ root_group }}"
    mode: "0644"
  with_items:
    - "{{ solr.prefix.bin }}/solr-{{ solr.version }}.tar.gz"
  register: solr_get_url_result

- name: Handle Solr update
  when: solr_get_url_result.changed
  block:
    - name: Stop Solr service
      ansible.builtin.service:
        name: solr
        state: stopped

    - name: Disable Solr service
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: "^solr_enable="
        line: 'solr_enable="NO"'
      with_items:
        - /etc/rc.conf

    - name: Remove old Solr version
      changed_when: yes
      ansible.builtin.command:
        cmd: >-
          find {{ item | quote }} -mindepth 1 -not -name solr-{{ solr.version | quote }}.tar.gz -delete
      with_items:
        - "{{ solr.prefix.bin }}"

    - name: Unarchive Solr
      ansible.builtin.unarchive:
        src: "{{ solr.prefix.bin }}/solr-{{ solr.version }}.tar.gz"
        dest: "{{ item }}"
        extra_opts:
          - --strip-components=1
        remote_src: yes
      with_items:
        - "{{ solr.prefix.bin }}"


- name: Sync Solr config
  ansible.posix.synchronize:
    src: "{{ solr.synced_config }}/"
    dest: "{{ item }}"
    rsync_opts:
      - --chown=solr:solr
      - --no-times
      - --checksum
    use_ssh_args: yes
  with_items:
    - "{{ solr.prefix.var }}"
  when: solr.synced_config
  notify: Restart Solr

- name: Enable Solr service
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^solr_enable="
    line: 'solr_enable="YES"'
  with_items:
    - /etc/rc.conf
  notify: Start Solr
