---
- name: Create program directory for Tika
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
  with_items:
    - "{{ solr.tika.prefix.bin }}"

- name: Download Tika
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/tika/{{ solr.tika.version }}/tika-server-standard-{{ solr.tika.version }}.jar"
    dest: "{{ solr.tika.prefix.bin }}/tika-server-{{ solr.tika.version }}.jar"
    checksum: "sha512:https://archive.apache.org/dist/tika/{{ solr.tika.version }}/tika-server-standard-{{ solr.tika.version }}.jar.sha512"
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
  notify: Restart Tika

- name: Install Tika service
  ansible.builtin.template:
    src: rc.d/tika
    dest: "{{ item }}"
    owner: root
    group: wheel
    mode: "0755"
  with_items:
    - /etc/rc.d/tika
  notify: Start Tika

- name: Enable Tika service
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^tika_enable="
    line: 'tika_enable="YES"'
  with_items:
    - /etc/rc.conf
  notify: Start Tika
