---
- name: Create program directory for Tika
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: "0755"
  with_items:
    - "{{ solr.prefix.tika }}"

- name: Create log directory for Tika
  ansible.builtin.file:
    path: "{{ solr.prefix.logs }}"
    state: directory
    owner: solr
    mode: "0755"

- name: Download Tika {{ solr.tika.version }}
  register: tika_get_url_result
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/tika/{{ solr.tika.version }}/tika-server-{{ tika_standard }}{{ solr.tika.version }}.jar"
    dest: "{{ solr.prefix.tika }}/tika-server.jar"
    checksum: "sha512:https://archive.apache.org/dist/tika/{{ solr.tika.version }}/tika-server-{{ tika_standard }}{{ solr.tika.version }}.jar.sha512"
    owner: root
    mode: "0755"
  vars:
    tika_standard: "{{ 'standard-' if solr.tika.version is version('2', '>=') else '' }}"
  notify: 
    - Start Tika
    - Restart Tika

- name: Stop and disable the native rc.d Tika service
  failed_when: no
  ansible.builtin.service:
    name: tika
    state: stopped
    enabled: no
  notify: 
    - Start Tika
    - Restart Tika

- name: Install Tika service
  ansible.builtin.template:
    src: supervisord.d/tika.conf
    dest: "/usr/local/etc/supervisord.d/tika.conf"
    owner: root
    group: wheel
    mode: "0755"
  notify: 
    - Start Tika
    - Restart Tika

- name: Reload supervisord configuration
  changed_when: no
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      sudo supervisorctl update
