---
- name: Create program directory for Tika
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ solr.tika.prefix.bin }}"

- name: Download Tika
  get_url:
    url: "https://archive.apache.org/dist/tika/tika-server-{{ solr.tika.version }}.jar"
    dest: "{{ item }}"
    checksum: "{{ solr.tika.checksum }}"
  with_items:
    - "{{ solr.tika.prefix.bin }}/tika-server-{{ solr.tika.version }}.jar"
  notify: Restart Tika

- name: Install Tika service
  template:
    src: rc.d/tika
    dest: "{{ item }}"
    owner: root
    group: wheel
    mode: 0755
  with_items:
    - /etc/rc.d/tika
  notify: Start Tika

- name: Enable Tika service
  lineinfile:
    path: "{{ item }}"
    regexp: "^tika_enable="
    line: 'tika_enable="YES"'
  with_items:
    - /etc/rc.conf
  notify: Start Tika
