---
- name: Start Solr
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update solr
      supervisorctl start solr
  register: solr_service_result

- name: Restart Solr
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update solr
      supervisorctl restart solr
  when: not (solr_service_result is defined and solr_service_result.changed)
