---
- name: Start Solr
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update solr
      supervisorctl start solr
  register: solr_service_result

- name: Restart Solr
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update solr
      supervisorctl restart solr
  when: not (solr_service_result is defined and solr_service_result.changed)

- name: Start Tika
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update tika
      supervisorctl start tika
  register: tika_service_result

- name: Restart Tika
  changed_when: yes
  ansible.builtin.shell:
    cmd: |
      set -e -u -o pipefail
      supervisorctl update tika
      supervisorctl restart tika
  when: not (tika_service_result is defined and tika_service_result.changed)
