[program:solr]
user=solr
command={{ solr.prefix.bin }}/bin/solr start -f{{ '' if solr.cloud | default(false) | bool else ' --user-managed' }}
startsecs=10
environment=PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin,SOLR_INCLUDE="{{ solr.prefix.bin }}/bin/solr.in.sh",SOLR_HOME="{{ solr.prefix.home }}",SOLR_HEAP="{{ solr.heap | default('512m') }}"
stdout_logfile={{ solr.prefix.logs }}/solr.log
redirect_stderr=true
